// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package sqlc

import (
	"time"
)

type Category struct {
	Name string
}

type Txn struct {
	ID          int64
	Timestamp   time.Time
	Amount      int64
	Category    string
	Description *string
}
